"""
Generates powerquery/queries.pq from the templates below.

Why generated rather than hand-written: the per-programme, per-item queries
(Phase 2) are ~60 near-identical one-liners (6 programmes x 10 items, plus
10 school-wide unions). Hand-typing that many is where copy-paste typos
live. Re-run this script if the programme list or item list changes:

    python3 generate_queries.py
"""

PROGRAMMES = [
    # (Programme name as stored in ModuleRegister, short code used in query names)
    ("Football Science", "FS"),
    ("Physical Education", "PE"),
    ("Sport and Exercise Science", "SES"),
    ("Sport Coaching", "COACH"),
    ("Sport Nutrition", "NUTR"),
    ("Sport Psychology", "PSYC"),
]

# The 10 standard "_MODULECODE_ITEM" tables found on every module sheet.
ITEMS = ["Meta", "LO", "Assess", "Weekly", "Hours", "Mapping", "Aims", "Syllabus", "Overview", "Notes"]

PREAMBLE = r'''section Section1;

// =====================================================================
// SPS Revalidation — module mapping queries
// Generated by powerquery/generate_queries.py — see powerquery/README.md
// =====================================================================
//
// Layout:
//   1. Settings          — the one thing you edit per machine
//   2. Source plumbing    — reads every workbook once, in one place
//   3. Module register    — reshapes "Modules by programme.xlsx" as-is
//   4. fnItemTable         — the one function every query below calls
//   5. Generated queries   — one per (programme x item), plus school-wide
//
// Design notes:
//   - "Single home" for shared modules needs no bookkeeping: SourceTables
//     pools every table from all 6 workbooks BEFORE anything is filtered
//     by programme, so a module physically stored in one workbook (e.g.
//     4093SPS, which only exists in the Sport Psychology file) still
//     surfaces correctly for every OTHER programme whose register entry
//     names it. The join is the mechanism — there is no HomeWorkbook
//     column to maintain.
//   - Junk rows filter themselves out: LISTS_Assess, template-sheet
//     tables, and the existing Query1/AllAssess table all fail the inner
//     join in fnItemTable because their derived "module code" (LISTS,
//     Template, AllAssess, ...) matches nothing in ModuleRegister.
//   - Sport Coaching's 4 provisional codes (5XX1SPS, 5XX2SPS, 6XX1SPS,
//     6XX2SPS) are treated as ordinary module codes, per instruction —
//     no special-case filtering for "TBC" status.
//   - Meta/Hours (key-value) and Aims/Syllabus/Overview/Notes (single-
//     column free text) are deliberately left in their raw per-record
//     shape here. Pivoting Meta/Hours into one row per module, and
//     combining the free-text items into one block per module, is a
//     Phase 3 (DASHBOARD view) concern layered on top of these queries
//     — not done here, so these stay simple, provable building blocks.

// ---------------------------------------------------------------------
// 1. SETTINGS — edit these two lines for your machine, nothing else
// ---------------------------------------------------------------------

// Local folder containing the 7 xlsx files (this repo, cloned locally).
// Used while the project develops against the GitHub repo, not SharePoint.
shared SourceFolder = "C:\Users\YourName\sps-ppr-2026";

// Flip to `true` only when ready to point at the live SharePoint site
// instead of the local folder above. Nothing below needs to change.
shared UseSharePoint = false;

// Kept for when UseSharePoint flips to true — not used while false.
shared SharePointSiteRoot = "https://ljmu.sharepoint.com/teams/SPSRe-validation2026Team";

// ---------------------------------------------------------------------
// 2. SOURCE PLUMBING — every workbook is read exactly once
// ---------------------------------------------------------------------

shared GetWorkbookFiles =
    let
        LocalSource = Folder.Files(SourceFolder),
        LocalWorkbooks = Table.SelectRows(LocalSource, each
            Text.Contains([Name], "AllModuleProformas")
            and (Text.EndsWith([Name], ".xlsx") or Text.EndsWith([Name], ".xlsm"))
        ),

        SharePointAllFiles = SharePoint.Files(SharePointSiteRoot, [ApiVersion = 15]),
        SharePointExcelFiles = Table.SelectRows(SharePointAllFiles, each
            Text.EndsWith([Name], ".xlsx") or Text.EndsWith([Name], ".xlsm")
        ),
        SharePointWorkbooks = Table.SelectRows(SharePointExcelFiles, each
            Text.Contains([Name], "AllModuleProformas")
        ),

        Result = if UseSharePoint then SharePointWorkbooks else LocalWorkbooks
    in
        Result;

shared GetRegisterFileContent =
    let
        LocalFiles = Folder.Files(SourceFolder),
        LocalMatch = Table.SelectRows(LocalFiles, each [Name] = "Modules by programme.xlsx"),
        LocalRegister = LocalMatch{0}[Content],

        SharePointFiles = SharePoint.Files(SharePointSiteRoot, [ApiVersion = 15]),
        SharePointMatch = Table.SelectRows(SharePointFiles, each [Name] = "Modules by programme.xlsx"),
        SharePointRegister = SharePointMatch{0}[Content],

        Result = if UseSharePoint then SharePointRegister else LocalRegister
    in
        Result;

// Every named Excel Table, from every workbook, in one pooled list.
// This — not any per-query source read — is what makes the "single
// home, many programmes" principle work without extra bookkeeping.
shared SourceTables =
    let
        Files = GetWorkbookFiles,
        AddWorkbookData = Table.AddColumn(Files, "Workbook", each Excel.Workbook([Content], true)),
        Expanded = Table.ExpandTableColumn(AddWorkbookData, "Workbook", {"Name", "Data", "Kind"}, {"TableName", "TableData", "Kind"}),
        OnlyTables = Table.SelectRows(Expanded, each [Kind] = "Table"),
        Trimmed = Table.SelectColumns(OnlyTables, {"Name", "TableName", "TableData"}),
        Renamed = Table.RenameColumns(Trimmed, {{"Name", "SourceWorkbook"}})
    in
        Renamed;

// "_4101SPS_Meta" (or "4101SPS_Meta") -> [ModuleCode = "4101SPS", ItemSuffix = "Meta"]
shared fnParseTableName = (tableName as text) as record =>
    let
        Clean = if Text.StartsWith(tableName, "_") then Text.Middle(tableName, 1) else tableName,
        Parts = Text.Split(Clean, "_"),
        Code = Parts{0},
        Item = Text.Combine(List.Skip(Parts, 1), "_")
    in
        [ModuleCode = Code, ItemSuffix = Item];

shared SourceTablesParsed =
    let
        Source = SourceTables,
        AddParsed = Table.AddColumn(Source, "Parsed", each fnParseTableName([TableName])),
        AddModuleCode = Table.AddColumn(AddParsed, "ModuleCode", each [Parsed][ModuleCode]),
        AddItemSuffix = Table.AddColumn(AddModuleCode, "ItemSuffix", each [Parsed][ItemSuffix]),
        Cleaned = Table.RemoveColumns(AddItemSuffix, {"Parsed"})
    in
        Cleaned;

// ---------------------------------------------------------------------
// 3. MODULE REGISTER — read "Modules by programme.xlsx" as it stands
// ---------------------------------------------------------------------
//
// Not a formal Table, just 6 side-by-side (code, title) column pairs.
// Rather than trust fixed row numbers (fragile if a row is ever
// inserted), every module row is recognised the same way a person
// would recognise one: its code ends in "SPS". That skips the
// programme-name header row, blank rows, and the SharePoint-folder
// footer row without needing to know which row number they're on.

shared RegisterBlocks = {
    [Programme = "Football Science",           ProgCode = "FS",    CodeCol = "Column2",  TitleCol = "Column3"],
    [Programme = "Physical Education",         ProgCode = "PE",    CodeCol = "Column8",  TitleCol = "Column9"],
    [Programme = "Sport and Exercise Science", ProgCode = "SES",   CodeCol = "Column14", TitleCol = "Column15"],
    [Programme = "Sport Coaching",              ProgCode = "COACH", CodeCol = "Column21", TitleCol = "Column22"],
    [Programme = "Sport Nutrition",             ProgCode = "NUTR",  CodeCol = "Column28", TitleCol = "Column29"],
    [Programme = "Sport Psychology",            ProgCode = "PSYC",  CodeCol = "Column34", TitleCol = "Column35"]
};

shared ModuleRegister =
    let
        Workbook = Excel.Workbook(GetRegisterFileContent, false),
        Sheet1Rows = Table.SelectRows(Workbook, each [Name] = "Sheet1"),
        Sheet1 = Sheet1Rows{0}[Data],

        ExtractBlock = (b as record) as table =>
            let
                CodeColName = b[CodeCol],
                TitleColName = b[TitleCol],
                Selected = Table.SelectColumns(Sheet1, {CodeColName, TitleColName}),
                Renamed = Table.RenameColumns(Selected, {{CodeColName, "ModuleCode"}, {TitleColName, "ModuleTitle"}}),
                OnlyModuleRows = Table.SelectRows(Renamed, each
                    [ModuleCode] <> null
                    and Text.EndsWith(Text.Trim(Text.From([ModuleCode])), "SPS")
                ),
                Tidy = Table.TransformColumns(OnlyModuleRows, {
                    {"ModuleCode", each Text.Trim(Text.From(_)), type text},
                    {"ModuleTitle", each Text.Trim(Text.From(_)), type text}
                }),
                AddProgramme = Table.AddColumn(Tidy, "Programme", each b[Programme]),
                AddProgCode = Table.AddColumn(AddProgramme, "ProgCode", each b[ProgCode])
            in
                Table.SelectColumns(AddProgCode, {"Programme", "ProgCode", "ModuleCode", "ModuleTitle"}),

        AllBlocks = List.Transform(RegisterBlocks, each ExtractBlock(_)),
        Combined = Table.Combine(AllBlocks)
    in
        Combined;

// ---------------------------------------------------------------------
// 4. fnItemTable — every query below is just a call to this
// ---------------------------------------------------------------------
//
// programmeFilter = a Programme name from RegisterBlocks, or `null` for
// every programme (the school-wide / "All_" queries).
// itemSuffix = one of Meta, LO, Assess, Weekly, Hours, Mapping, Aims,
// Syllabus, Overview, Notes.
//
// A shared module (say 4093SPS, physically only in the Sport Psychology
// workbook) has exactly one row in SourceTablesParsed per item, but can
// have several matching rows in ModuleRegister (one per programme that
// lists it). The inner join fans it out correctly: it appears once for
// every programme that claims it, sourced from wherever it actually
// lives — which is the "single home, several users" principle in
// practice, not as a rule that has to be separately enforced.

shared fnItemTable = (programmeFilter as nullable text, itemSuffix as text) as table =>
    let
        FilteredByItem = Table.SelectRows(SourceTablesParsed, each [ItemSuffix] = itemSuffix),
        Joined = Table.NestedJoin(FilteredByItem, {"ModuleCode"}, ModuleRegister, {"ModuleCode"}, "Register", JoinKind.Inner),
        ExpandedRegister = Table.ExpandTableColumn(Joined, "Register", {"Programme", "ProgCode", "ModuleTitle"}, {"Programme", "ProgCode", "ModuleTitle"}),
        FilteredByProgramme = if programmeFilter = null then ExpandedRegister else Table.SelectRows(ExpandedRegister, each [Programme] = programmeFilter),
        // Union of column names across every matched module's table, not just
        // the first one — one Football Science "_Notes" table (6304SPS) has a
        // stray extra column versus the other 77, and this keeps that from
        // silently dropping columns or erroring depending on row order.
        AllColumnNames =
            if Table.IsEmpty(FilteredByProgramme) then
                {}
            else
                List.Distinct(List.Combine(List.Transform(FilteredByProgramme[TableData], each Table.ColumnNames(_)))),
        ExpandedContent =
            if Table.IsEmpty(FilteredByProgramme) then
                FilteredByProgramme
            else
                Table.ExpandTableColumn(FilteredByProgramme, "TableData", AllColumnNames)
    in
        ExpandedContent;

// ---------------------------------------------------------------------
// 5. GENERATED QUERIES — one per (programme x item), plus school-wide
// ---------------------------------------------------------------------
'''.lstrip("\n")


def build_queries_block() -> str:
    lines = []
    lines.append("// --- per-programme -----------------------------------------------------\n")
    for programme, code in PROGRAMMES:
        lines.append(f"// {programme}")
        for item in ITEMS:
            lines.append(f'shared {code}_{item} = fnItemTable("{programme}", "{item}");')
        lines.append("")

    lines.append("// --- school-wide (all programmes, unfiltered) ---------------------------\n")
    for item in ITEMS:
        lines.append(f'shared All_{item} = fnItemTable(null, "{item}");')

    return "\n".join(lines) + "\n"


def main():
    out_path = "queries.pq"
    content = PREAMBLE + "\n" + build_queries_block()
    with open(out_path, "w") as f:
        f.write(content)
    n_programme_queries = len(PROGRAMMES) * len(ITEMS)
    n_school_queries = len(ITEMS)
    print(f"Wrote {out_path}: {n_programme_queries} per-programme queries + {n_school_queries} school-wide queries "
          f"({n_programme_queries + n_school_queries + 7} shared bindings total).")


if __name__ == "__main__":
    main()
