section Section1;

// =====================================================================
// SPS Revalidation — module mapping queries
// Generated by powerquery/generate_queries.py — see powerquery/README.md
// =====================================================================
//
// Layout:
//   1. Settings          — the one thing you edit per machine
//   2. Source plumbing    — reads every workbook once, in one place
//   3. Module register    — reshapes "Modules by programme.xlsx" as-is
//   4. fnItemTable         — the one function every query below calls
//   5. Generated queries   — one per (programme x item), plus school-wide
//
// Design notes:
//   - "Single home" for shared modules needs no bookkeeping: SourceTables
//     pools every table from all 6 workbooks BEFORE anything is filtered
//     by programme, so a module physically stored in one workbook (e.g.
//     4093SPS, which only exists in the Sport Psychology file) still
//     surfaces correctly for every OTHER programme whose register entry
//     names it. The join is the mechanism — there is no HomeWorkbook
//     column to maintain.
//   - Junk rows filter themselves out: LISTS_Assess, template-sheet
//     tables, and the existing Query1/AllAssess table all fail the inner
//     join in fnItemTable because their derived "module code" (LISTS,
//     Template, AllAssess, ...) matches nothing in ModuleRegister.
//   - Sport Coaching's 4 provisional codes (5XX1SPS, 5XX2SPS, 6XX1SPS,
//     6XX2SPS) are treated as ordinary module codes, per instruction —
//     no special-case filtering for "TBC" status.
//   - A module code can exist in more than one workbook for two different
//     reasons: genuine sharing (the code exists in exactly one workbook;
//     several programmes list it) or a code collision (the SAME code
//     exists in two workbooks as two unrelated modules — verified case:
//     4202SPS is both PE's "Learning in PE and Sport Contexts" and Sport
//     Coaching's "Learning Theory and Practice 1"). fnItemTable resolves
//     this by preferring, for each (Programme, ModuleCode), the table
//     from that programme's own workbook when one exists there, and only
//     falling back to another workbook when it doesn't — see step 4.
//   - Meta/Hours (key-value) and Aims/Syllabus/Overview/Notes (single-
//     column free text) are deliberately left in their raw per-record
//     shape here. Pivoting Meta/Hours into one row per module, and
//     combining the free-text items into one block per module, is a
//     Phase 3 (DASHBOARD view) concern layered on top of these queries
//     — not done here, so these stay simple, provable building blocks.

// ---------------------------------------------------------------------
// 1. SETTINGS — edit these two lines for your machine, nothing else
// ---------------------------------------------------------------------

// Local folder containing the 7 xlsx files (this repo, cloned locally).
// Used while the project develops against the GitHub repo, not SharePoint.
shared SourceFolder = "C:\Users\YourName\sps-ppr-2026";

// Flip to `true` only when ready to point at the live SharePoint site
// instead of the local folder above. Nothing below needs to change.
shared UseSharePoint = false;

// Kept for when UseSharePoint flips to true — not used while false.
shared SharePointSiteRoot = "https://ljmu.sharepoint.com/teams/SPSRe-validation2026Team";

// ---------------------------------------------------------------------
// 2. SOURCE PLUMBING — every workbook is read exactly once
// ---------------------------------------------------------------------

shared GetWorkbookFiles =
    let
        LocalSource = Folder.Files(SourceFolder),
        LocalWorkbooks = Table.SelectRows(LocalSource, each
            Text.Contains([Name], "AllModuleProformas")
            and (Text.EndsWith([Name], ".xlsx") or Text.EndsWith([Name], ".xlsm"))
            // Exclude Excel's own lock file for whichever workbook is currently
            // open (~$Football Science - AllModuleProformas.xlsx) and macOS's
            // AppleDouble sidecar files (._Football Science - ...) — both match
            // the filters above but aren't real workbooks, and Excel.Workbook()
            // on either throws "File contains corrupted data".
            and not Text.StartsWith([Name], "~$")
            and not Text.StartsWith([Name], ".")
        ),

        SharePointAllFiles = SharePoint.Files(SharePointSiteRoot, [ApiVersion = 15]),
        SharePointExcelFiles = Table.SelectRows(SharePointAllFiles, each
            Text.EndsWith([Name], ".xlsx") or Text.EndsWith([Name], ".xlsm")
        ),
        SharePointWorkbooks = Table.SelectRows(SharePointExcelFiles, each
            Text.Contains([Name], "AllModuleProformas")
        ),

        Result = if UseSharePoint then SharePointWorkbooks else LocalWorkbooks
    in
        Result;

shared GetRegisterFileContent =
    let
        LocalFiles = Folder.Files(SourceFolder),
        LocalMatch = Table.SelectRows(LocalFiles, each [Name] = "Modules by programme.xlsx"),
        LocalRegister = LocalMatch{0}[Content],

        SharePointFiles = SharePoint.Files(SharePointSiteRoot, [ApiVersion = 15]),
        SharePointMatch = Table.SelectRows(SharePointFiles, each [Name] = "Modules by programme.xlsx"),
        SharePointRegister = SharePointMatch{0}[Content],

        Result = if UseSharePoint then SharePointRegister else LocalRegister
    in
        Result;

// Every named Excel Table, from every workbook, in one pooled list.
// This — not any per-query source read — is what makes the "single
// home, many programmes" principle work without extra bookkeeping.
shared SourceTables =
    let
        Files = GetWorkbookFiles,
        AddWorkbookData = Table.AddColumn(Files, "Workbook", each Excel.Workbook([Content], true)),
        Expanded = Table.ExpandTableColumn(AddWorkbookData, "Workbook", {"Name", "Data", "Kind"}, {"TableName", "TableData", "Kind"}),
        OnlyTables = Table.SelectRows(Expanded, each [Kind] = "Table"),
        Trimmed = Table.SelectColumns(OnlyTables, {"Name", "TableName", "TableData"}),
        Renamed = Table.RenameColumns(Trimmed, {{"Name", "SourceWorkbook"}})
    in
        Renamed;

// "_4101SPS_Meta" (or "4101SPS_Meta") -> [ModuleCode = "4101SPS", ItemSuffix = "Meta"]
shared fnParseTableName = (tableName as text) as record =>
    let
        Clean = if Text.StartsWith(tableName, "_") then Text.Middle(tableName, 1) else tableName,
        Parts = Text.Split(Clean, "_"),
        Code = Parts{0},
        Item = Text.Combine(List.Skip(Parts, 1), "_")
    in
        [ModuleCode = Code, ItemSuffix = Item];

shared SourceTablesParsed =
    let
        Source = SourceTables,
        AddParsed = Table.AddColumn(Source, "Parsed", each fnParseTableName([TableName])),
        AddModuleCode = Table.AddColumn(AddParsed, "ModuleCode", each [Parsed][ModuleCode]),
        AddItemSuffix = Table.AddColumn(AddModuleCode, "ItemSuffix", each [Parsed][ItemSuffix]),
        Cleaned = Table.RemoveColumns(AddItemSuffix, {"Parsed"})
    in
        Cleaned;

// ---------------------------------------------------------------------
// 3. MODULE REGISTER — read "Modules by programme.xlsx" as it stands
// ---------------------------------------------------------------------
//
// Not a formal Table, just 6 side-by-side (code, title) column pairs.
// Rather than trust fixed row numbers (fragile if a row is ever
// inserted), every module row is recognised the same way a person
// would recognise one: its code ends in "SPS". That skips the
// programme-name header row, blank rows, and the SharePoint-folder
// footer row without needing to know which row number they're on.

// Excel.Workbook(..., false) numbers generic columns from the sheet's USED
// RANGE, not from absolute column A. This sheet's used range is B4:AI40
// (column A is entirely blank), so Column1 = worksheet column B, Column2 =
// C, and so on — every absolute column letter maps to "its own position
// minus 1" here (worksheet AI, the last used column, is Column34, not
// Column35). Verified against a live "Column35 not found" error — if this
// register's layout ever changes, so does this offset.
shared RegisterBlocks = {
    [Programme = "Football Science",           ProgCode = "FS",    CodeCol = "Column1",  TitleCol = "Column2"],
    [Programme = "Physical Education",         ProgCode = "PE",    CodeCol = "Column7",  TitleCol = "Column8"],
    [Programme = "Sport and Exercise Science", ProgCode = "SES",   CodeCol = "Column13", TitleCol = "Column14"],
    [Programme = "Sport Coaching",              ProgCode = "COACH", CodeCol = "Column20", TitleCol = "Column21"],
    [Programme = "Sport Nutrition",             ProgCode = "NUTR",  CodeCol = "Column27", TitleCol = "Column28"],
    [Programme = "Sport Psychology",            ProgCode = "PSYC",  CodeCol = "Column33", TitleCol = "Column34"]
};

shared ModuleRegister =
    let
        Workbook = Excel.Workbook(GetRegisterFileContent, false),
        Sheet1Rows = Table.SelectRows(Workbook, each [Name] = "Sheet1"),
        Sheet1 = Sheet1Rows{0}[Data],

        ExtractBlock = (b as record) as table =>
            let
                CodeColName = b[CodeCol],
                TitleColName = b[TitleCol],
                Selected = Table.SelectColumns(Sheet1, {CodeColName, TitleColName}),
                Renamed = Table.RenameColumns(Selected, {{CodeColName, "ModuleCode"}, {TitleColName, "ModuleTitle"}}),
                OnlyModuleRows = Table.SelectRows(Renamed, each
                    [ModuleCode] <> null
                    and Text.EndsWith(Text.Trim(Text.From([ModuleCode])), "SPS")
                ),
                Tidy = Table.TransformColumns(OnlyModuleRows, {
                    {"ModuleCode", each Text.Trim(Text.From(_)), type text},
                    {"ModuleTitle", each Text.Trim(Text.From(_)), type text}
                }),
                AddProgramme = Table.AddColumn(Tidy, "Programme", each b[Programme]),
                AddProgCode = Table.AddColumn(AddProgramme, "ProgCode", each b[ProgCode])
            in
                Table.SelectColumns(AddProgCode, {"Programme", "ProgCode", "ModuleCode", "ModuleTitle"}),

        AllBlocks = List.Transform(RegisterBlocks, each ExtractBlock(_)),
        Combined = Table.Combine(AllBlocks)
    in
        Combined;

// ---------------------------------------------------------------------
// 4. fnItemTable — every query below is just a call to this
// ---------------------------------------------------------------------
//
// programmeFilter = a Programme name from RegisterBlocks, or `null` for
// every programme (the school-wide / "All_" queries).
// itemSuffix = one of Meta, LO, Assess, Weekly, Hours, Mapping, Aims,
// Syllabus, Overview, Notes.
//
// A shared module (say 4093SPS, physically only in the Sport Psychology
// workbook) has exactly one row in SourceTablesParsed per item, but can
// have several matching rows in ModuleRegister (one per programme that
// lists it). The inner join fans it out correctly: it appears once for
// every programme that claims it, sourced from wherever it actually
// lives — which is the "single home, several users" principle in
// practice, not as a rule that has to be separately enforced.
//
// Step 4 handles the other case: a module code that exists in MORE THAN
// ONE workbook. Since workbooks are named "<Programme> - AllModuleProformas",
// a Programme's own workbook is recognisable directly from SourceWorkbook.
// For each (Programme, ModuleCode), prefer the row(s) from that
// programme's own workbook when any exist there; only keep rows from
// elsewhere when the programme's own workbook has none for that code.
// This resolves the verified 4202SPS collision (PE and Sport Coaching
// each get their own module back, not each other's) while still letting
// genuinely shared codes (4093SPS, 6091SPS, ...) fall back correctly.

shared fnItemTable = (programmeFilter as nullable text, itemSuffix as text) as table =>
    let
        FilteredByItem = Table.SelectRows(SourceTablesParsed, each [ItemSuffix] = itemSuffix),
        Joined = Table.NestedJoin(FilteredByItem, {"ModuleCode"}, ModuleRegister, {"ModuleCode"}, "Register", JoinKind.Inner),
        ExpandedRegister = Table.ExpandTableColumn(Joined, "Register", {"Programme", "ProgCode", "ModuleTitle"}, {"Programme", "ProgCode", "ModuleTitle"}),
        FilteredByProgramme = if programmeFilter = null then ExpandedRegister else Table.SelectRows(ExpandedRegister, each [Programme] = programmeFilter),

        // Resolve (Programme, ModuleCode) pairs matched to more than one
        // physical table: prefer the programme's own workbook.
        Grouped = Table.Group(FilteredByProgramme, {"Programme", "ModuleCode"}, {{"Rows", each _, type table}}),
        Resolved = Table.AddColumn(Grouped, "Chosen", (g) =>
            let
                Candidates = g[Rows],
                OwnProgramme = g[Programme],
                OwnWorkbook = Table.SelectRows(Candidates, each Text.StartsWith([SourceWorkbook], OwnProgramme))
            in
                if Table.RowCount(OwnWorkbook) > 0 then OwnWorkbook else Candidates
        ),
        Recombined = Table.Combine(Resolved[Chosen]),

        // Union of column names across every matched module's table, not just
        // the first one — one Football Science "_Notes" table (6304SPS) has a
        // stray extra column versus the other 77, and this keeps that from
        // silently dropping columns or erroring depending on row order.
        AllColumnNames =
            if Table.IsEmpty(Recombined) then
                {}
            else
                List.Distinct(List.Combine(List.Transform(Recombined[TableData], each Table.ColumnNames(_)))),
        ExpandedContent =
            if Table.IsEmpty(Recombined) then
                Recombined
            else
                Table.ExpandTableColumn(Recombined, "TableData", AllColumnNames)
    in
        ExpandedContent;

// ---------------------------------------------------------------------
// 5. GENERATED QUERIES — one per (programme x item), plus school-wide
// ---------------------------------------------------------------------

// --- per-programme -----------------------------------------------------

// Football Science
shared FS_Meta = fnItemTable("Football Science", "Meta");
shared FS_LO = fnItemTable("Football Science", "LO");
shared FS_Assess = fnItemTable("Football Science", "Assess");
shared FS_Weekly = fnItemTable("Football Science", "Weekly");
shared FS_Hours = fnItemTable("Football Science", "Hours");
shared FS_Mapping = fnItemTable("Football Science", "Mapping");
shared FS_Aims = fnItemTable("Football Science", "Aims");
shared FS_Syllabus = fnItemTable("Football Science", "Syllabus");
shared FS_Overview = fnItemTable("Football Science", "Overview");
shared FS_Notes = fnItemTable("Football Science", "Notes");

// Physical Education
shared PE_Meta = fnItemTable("Physical Education", "Meta");
shared PE_LO = fnItemTable("Physical Education", "LO");
shared PE_Assess = fnItemTable("Physical Education", "Assess");
shared PE_Weekly = fnItemTable("Physical Education", "Weekly");
shared PE_Hours = fnItemTable("Physical Education", "Hours");
shared PE_Mapping = fnItemTable("Physical Education", "Mapping");
shared PE_Aims = fnItemTable("Physical Education", "Aims");
shared PE_Syllabus = fnItemTable("Physical Education", "Syllabus");
shared PE_Overview = fnItemTable("Physical Education", "Overview");
shared PE_Notes = fnItemTable("Physical Education", "Notes");

// Sport and Exercise Science
shared SES_Meta = fnItemTable("Sport and Exercise Science", "Meta");
shared SES_LO = fnItemTable("Sport and Exercise Science", "LO");
shared SES_Assess = fnItemTable("Sport and Exercise Science", "Assess");
shared SES_Weekly = fnItemTable("Sport and Exercise Science", "Weekly");
shared SES_Hours = fnItemTable("Sport and Exercise Science", "Hours");
shared SES_Mapping = fnItemTable("Sport and Exercise Science", "Mapping");
shared SES_Aims = fnItemTable("Sport and Exercise Science", "Aims");
shared SES_Syllabus = fnItemTable("Sport and Exercise Science", "Syllabus");
shared SES_Overview = fnItemTable("Sport and Exercise Science", "Overview");
shared SES_Notes = fnItemTable("Sport and Exercise Science", "Notes");

// Sport Coaching
shared COACH_Meta = fnItemTable("Sport Coaching", "Meta");
shared COACH_LO = fnItemTable("Sport Coaching", "LO");
shared COACH_Assess = fnItemTable("Sport Coaching", "Assess");
shared COACH_Weekly = fnItemTable("Sport Coaching", "Weekly");
shared COACH_Hours = fnItemTable("Sport Coaching", "Hours");
shared COACH_Mapping = fnItemTable("Sport Coaching", "Mapping");
shared COACH_Aims = fnItemTable("Sport Coaching", "Aims");
shared COACH_Syllabus = fnItemTable("Sport Coaching", "Syllabus");
shared COACH_Overview = fnItemTable("Sport Coaching", "Overview");
shared COACH_Notes = fnItemTable("Sport Coaching", "Notes");

// Sport Nutrition
shared NUTR_Meta = fnItemTable("Sport Nutrition", "Meta");
shared NUTR_LO = fnItemTable("Sport Nutrition", "LO");
shared NUTR_Assess = fnItemTable("Sport Nutrition", "Assess");
shared NUTR_Weekly = fnItemTable("Sport Nutrition", "Weekly");
shared NUTR_Hours = fnItemTable("Sport Nutrition", "Hours");
shared NUTR_Mapping = fnItemTable("Sport Nutrition", "Mapping");
shared NUTR_Aims = fnItemTable("Sport Nutrition", "Aims");
shared NUTR_Syllabus = fnItemTable("Sport Nutrition", "Syllabus");
shared NUTR_Overview = fnItemTable("Sport Nutrition", "Overview");
shared NUTR_Notes = fnItemTable("Sport Nutrition", "Notes");

// Sport Psychology
shared PSYC_Meta = fnItemTable("Sport Psychology", "Meta");
shared PSYC_LO = fnItemTable("Sport Psychology", "LO");
shared PSYC_Assess = fnItemTable("Sport Psychology", "Assess");
shared PSYC_Weekly = fnItemTable("Sport Psychology", "Weekly");
shared PSYC_Hours = fnItemTable("Sport Psychology", "Hours");
shared PSYC_Mapping = fnItemTable("Sport Psychology", "Mapping");
shared PSYC_Aims = fnItemTable("Sport Psychology", "Aims");
shared PSYC_Syllabus = fnItemTable("Sport Psychology", "Syllabus");
shared PSYC_Overview = fnItemTable("Sport Psychology", "Overview");
shared PSYC_Notes = fnItemTable("Sport Psychology", "Notes");

// --- school-wide (all programmes, unfiltered) ---------------------------

shared All_Meta = fnItemTable(null, "Meta");
shared All_LO = fnItemTable(null, "LO");
shared All_Assess = fnItemTable(null, "Assess");
shared All_Weekly = fnItemTable(null, "Weekly");
shared All_Hours = fnItemTable(null, "Hours");
shared All_Mapping = fnItemTable(null, "Mapping");
shared All_Aims = fnItemTable(null, "Aims");
shared All_Syllabus = fnItemTable(null, "Syllabus");
shared All_Overview = fnItemTable(null, "Overview");
shared All_Notes = fnItemTable(null, "Notes");
