section Section1;

// =====================================================================
// SPS Revalidation — module mapping queries
// Generated by powerquery/generate_queries.py — see powerquery/README.md
// =====================================================================
//
// Layout:
//   1. Settings          — what you edit per machine / per deployment
//   2. Source plumbing    — reads every workbook once, in one place
//   3. Module register    — reshapes "Modules by programme.xlsx" as-is
//   4. fnItemTable         — the one function every query below calls
//   5. Wide views          — Meta/Hours reshaped to one row per module
//   6. Graduate skills coverage
//   7. Generated queries   — one per (programme x item), plus school-wide
//
// Design notes:
//   - "Single home" for shared modules needs no bookkeeping: SourceTables
//     pools every table from all 6 workbooks BEFORE anything is filtered
//     by programme, so a module physically stored in one workbook (e.g.
//     4093SPS, which only exists in the Sport Psychology file) still
//     surfaces correctly for every OTHER programme whose register entry
//     names it. The join is the mechanism — there is no HomeWorkbook
//     column to maintain.
//   - Junk rows filter themselves out: LISTS_Assess, template-sheet
//     tables, and the existing Query1/AllAssess table all fail the inner
//     join in fnItemTable because their derived "module code" (LISTS,
//     Template, AllAssess, ...) matches nothing in ModuleRegister.
//   - Sport Coaching's 4 provisional codes (5XX1SPS, 5XX2SPS, 6XX1SPS,
//     6XX2SPS) are treated as ordinary module codes, per instruction —
//     no special-case filtering for "TBC" status.
//   - A module code can exist in more than one workbook for two different
//     reasons: genuine sharing (the code exists in exactly one workbook;
//     several programmes list it) or a code collision (the SAME code
//     exists in two workbooks as two unrelated modules — verified case:
//     4202SPS is both PE's "Learning in PE and Sport Contexts" and Sport
//     Coaching's "Learning Theory and Practice 1"). fnItemTable resolves
//     this by preferring, for each (Programme, ModuleCode), the table
//     from that programme's own workbook when one exists there, and only
//     falling back to another workbook when it doesn't — see step 4.
//   - Meta/Hours (key-value) are deliberately left in their raw per-record
//     shape in step 4. Pivoting them into one row per module is step 5,
//     layered on top rather than mixed into the raw extraction.
//   - Only Meta, LO, Assess, Hours and Mapping are generated below — the
//     5 items relevant to assessment/LO/hours mapping. Weekly, Aims,
//     Syllabus, Overview and Notes are narrative/descriptive content, not
//     mapping data, so no queries are generated for them (fnItemTable
//     still supports any item suffix if that changes).

// ---------------------------------------------------------------------
// 1. SETTINGS
// ---------------------------------------------------------------------

// No local-folder option here, on purpose: this file is for wherever the
// workbook might actually be opened, including Excel for the web, which
// doesn't support Folder.Files (local filesystem access) at all -- not
// even inside an unused branch of an if. For local desktop-only testing
// against a git clone of this repo, use queries.pq instead.
shared SharePointSiteRoot = "https://ljmu.sharepoint.com/teams/SPSRe-validation2026Team";

// ---------------------------------------------------------------------
// 2. SOURCE PLUMBING — every workbook is read exactly once
// ---------------------------------------------------------------------

shared GetWorkbookFiles =
    let
        AllFiles = SharePoint.Files(SharePointSiteRoot, [ApiVersion = 15]),
        ExcelFiles = Table.SelectRows(AllFiles, each
            Text.EndsWith([Name], ".xlsx") or Text.EndsWith([Name], ".xlsm")
        ),
        Workbooks = Table.SelectRows(ExcelFiles, each
            Text.Contains([Name], "AllModuleProformas")
        )
    in
        Workbooks;

shared GetRegisterFileContent =
    let
        // Case/whitespace-insensitive: an exact match here is fragile the
        // moment this file gets re-uploaded to SharePoint under a slightly
        // different name (trailing space, different capitalisation) --
        // and a silent zero-row match fails downstream as an unhelpful
        // "not enough elements" error, not something that points at this.
        IsRegisterFile = (name as text) as logical =>
            Text.Trim(Text.Lower(name)) = "modules by programme.xlsx",

        AllFiles = SharePoint.Files(SharePointSiteRoot, [ApiVersion = 15]),
        Match = Table.SelectRows(AllFiles, each IsRegisterFile([Name])),
        Result = Match{0}[Content]
    in
        Result;

// Every named Excel Table, from every workbook, in one pooled list.
// This — not any per-query source read — is what makes the "single
// home, many programmes" principle work without extra bookkeeping.
//
// Table.Buffer here matters: SourceTables is referenced by every one of
// the 30+ downstream queries below. Without forcing it to materialize
// once, a refresh can re-open and re-scan all 6 workbooks once PER
// downstream query instead of once total — the difference between a
// multi-minute refresh and a fast one. (Also worth checking, outside
// this file: Power Query Editor -> File -> Options and Settings ->
// Query Options -> Privacy -> "Always ignore Privacy Level settings".
// Mismatched privacy levels across sources force the same kind of
// isolated per-query re-evaluation that buffering is working around.)
shared SourceTables =
    let
        Files = GetWorkbookFiles,
        AddWorkbookData = Table.AddColumn(Files, "Workbook", each Excel.Workbook([Content], true)),
        Expanded = Table.ExpandTableColumn(AddWorkbookData, "Workbook", {"Name", "Data", "Kind"}, {"TableName", "TableData", "Kind"}),
        OnlyTables = Table.SelectRows(Expanded, each [Kind] = "Table"),
        Trimmed = Table.SelectColumns(OnlyTables, {"Name", "TableName", "TableData"}),
        Renamed = Table.RenameColumns(Trimmed, {{"Name", "SourceWorkbook"}}),
        Buffered = Table.Buffer(Renamed)
    in
        Buffered;

// "_4101SPS_Meta" (or "4101SPS_Meta") -> [ModuleCode = "4101SPS", ItemSuffix = "Meta"]
shared fnParseTableName = (tableName as text) as record =>
    let
        Clean = if Text.StartsWith(tableName, "_") then Text.Middle(tableName, 1) else tableName,
        Parts = Text.Split(Clean, "_"),
        Code = Parts{0},
        Item = Text.Combine(List.Skip(Parts, 1), "_")
    in
        [ModuleCode = Code, ItemSuffix = Item];

// Kept in sync with ITEMS in generate_queries.py — the items actually
// queried below. Filtering to these here (not just inside fnItemTable)
// means SourceTablesParsed never carries the other 5 items' rows
// (Weekly, Aims, Syllabus, Overview, Notes) through the buffer at all.
shared RelevantItems = {"Meta", "LO", "Assess", "Hours", "Mapping"};

shared SourceTablesParsed =
    let
        Source = SourceTables,
        AddParsed = Table.AddColumn(Source, "Parsed", each fnParseTableName([TableName])),
        AddModuleCode = Table.AddColumn(AddParsed, "ModuleCode", each [Parsed][ModuleCode]),
        AddItemSuffix = Table.AddColumn(AddModuleCode, "ItemSuffix", each [Parsed][ItemSuffix]),
        Cleaned = Table.RemoveColumns(AddItemSuffix, {"Parsed"}),
        OnlyRelevantItems = Table.SelectRows(Cleaned, each List.Contains(RelevantItems, [ItemSuffix])),
        Buffered = Table.Buffer(OnlyRelevantItems)
    in
        Buffered;

// ---------------------------------------------------------------------
// 3. MODULE REGISTER — read "Modules by programme.xlsx" as it stands
// ---------------------------------------------------------------------
//
// Not a formal Table, just 6 side-by-side (code, title) column pairs.
// Rather than trust fixed row numbers (fragile if a row is ever
// inserted), every module row is recognised the same way a person
// would recognise one: its code ends in "SPS". That skips the
// programme-name header row, blank rows, and the SharePoint-folder
// footer row without needing to know which row number they're on.

// Excel.Workbook(..., false) numbers generic columns from the sheet's USED
// RANGE, not from absolute column A. This sheet's used range is B4:AI40
// (column A is entirely blank), so Column1 = worksheet column B, Column2 =
// C, and so on — every absolute column letter maps to "its own position
// minus 1" here (worksheet AI, the last used column, is Column34, not
// Column35). Verified against a live "Column35 not found" error — if this
// register's layout ever changes, so does this offset.
shared RegisterBlocks = {
    [Programme = "Football Science",           ProgCode = "FS",    CodeCol = "Column1",  TitleCol = "Column2"],
    [Programme = "Physical Education",         ProgCode = "PE",    CodeCol = "Column7",  TitleCol = "Column8"],
    [Programme = "Sport and Exercise Science", ProgCode = "SES",   CodeCol = "Column13", TitleCol = "Column14"],
    [Programme = "Sport Coaching",              ProgCode = "COACH", CodeCol = "Column20", TitleCol = "Column21"],
    [Programme = "Sport Nutrition",             ProgCode = "NUTR",  CodeCol = "Column27", TitleCol = "Column28"],
    [Programme = "Sport Psychology",            ProgCode = "PSYC",  CodeCol = "Column33", TitleCol = "Column34"]
};

shared ModuleRegister =
    let
        Workbook = Excel.Workbook(GetRegisterFileContent, false),
        Sheet1Rows = Table.SelectRows(Workbook, each [Name] = "Sheet1"),
        Sheet1 = Sheet1Rows{0}[Data],

        ExtractBlock = (b as record) as table =>
            let
                CodeColName = b[CodeCol],
                TitleColName = b[TitleCol],
                Selected = Table.SelectColumns(Sheet1, {CodeColName, TitleColName}),
                Renamed = Table.RenameColumns(Selected, {{CodeColName, "ModuleCode"}, {TitleColName, "ModuleTitle"}}),
                OnlyModuleRows = Table.SelectRows(Renamed, each
                    [ModuleCode] <> null
                    and Text.EndsWith(Text.Trim(Text.From([ModuleCode])), "SPS")
                ),
                Tidy = Table.TransformColumns(OnlyModuleRows, {
                    {"ModuleCode", each Text.Trim(Text.From(_)), type text},
                    {"ModuleTitle", each Text.Trim(Text.From(_)), type text}
                }),
                AddProgramme = Table.AddColumn(Tidy, "Programme", each b[Programme]),
                AddProgCode = Table.AddColumn(AddProgramme, "ProgCode", each b[ProgCode])
            in
                Table.SelectColumns(AddProgCode, {"Programme", "ProgCode", "ModuleCode", "ModuleTitle"}),

        AllBlocks = List.Transform(RegisterBlocks, each ExtractBlock(_)),
        Combined = Table.Combine(AllBlocks),
        Buffered = Table.Buffer(Combined)
    in
        Buffered;

// ---------------------------------------------------------------------
// 4. fnItemTable — every query below is just a call to this
// ---------------------------------------------------------------------
//
// programmeFilter = a Programme name from RegisterBlocks, or `null` for
// every programme (the school-wide / "All_" queries).
// itemSuffix = one of Meta, LO, Assess, Weekly, Hours, Mapping, Aims,
// Syllabus, Overview, Notes.
//
// A shared module (say 4093SPS, physically only in the Sport Psychology
// workbook) has exactly one row in SourceTablesParsed per item, but can
// have several matching rows in ModuleRegister (one per programme that
// lists it). The inner join fans it out correctly: it appears once for
// every programme that claims it, sourced from wherever it actually
// lives — which is the "single home, several users" principle in
// practice, not as a rule that has to be separately enforced.
//
// Step 4 handles the other case: a module code that exists in MORE THAN
// ONE workbook. Since workbooks are named "<Programme> - AllModuleProformas",
// a Programme's own workbook is recognisable directly from SourceWorkbook.
// For each (Programme, ModuleCode), prefer the row(s) from that
// programme's own workbook when any exist there; only keep rows from
// elsewhere when the programme's own workbook has none for that code.
// This resolves the verified 4202SPS collision (PE and Sport Coaching
// each get their own module back, not each other's) while still letting
// genuinely shared codes (4093SPS, 6091SPS, ...) fall back correctly.

shared fnItemTable = (programmeFilter as nullable text, itemSuffix as text) as table =>
    let
        FilteredByItem = Table.SelectRows(SourceTablesParsed, each [ItemSuffix] = itemSuffix),
        Joined = Table.NestedJoin(FilteredByItem, {"ModuleCode"}, ModuleRegister, {"ModuleCode"}, "Register", JoinKind.Inner),
        ExpandedRegister = Table.ExpandTableColumn(Joined, "Register", {"Programme", "ProgCode", "ModuleTitle"}, {"Programme", "ProgCode", "ModuleTitle"}),
        FilteredByProgramme = if programmeFilter = null then ExpandedRegister else Table.SelectRows(ExpandedRegister, each [Programme] = programmeFilter),

        // Resolve (Programme, ModuleCode) pairs matched to more than one
        // physical table: prefer the programme's own workbook.
        Grouped = Table.Group(FilteredByProgramme, {"Programme", "ModuleCode"}, {{"Rows", each _, type table}}),
        Resolved = Table.AddColumn(Grouped, "Chosen", (g) =>
            let
                Candidates = g[Rows],
                OwnProgramme = g[Programme],
                OwnWorkbook = Table.SelectRows(Candidates, each Text.StartsWith([SourceWorkbook], OwnProgramme))
            in
                if Table.RowCount(OwnWorkbook) > 0 then OwnWorkbook else Candidates
        ),
        Recombined = Table.Combine(Resolved[Chosen]),

        // Union of column names across every matched module's table, not just
        // the first one — one Football Science "_Notes" table (6304SPS) has a
        // stray extra column versus the other 77, and this keeps that from
        // silently dropping columns or erroring depending on row order.
        AllColumnNames =
            if Table.IsEmpty(Recombined) then
                {}
            else
                List.Distinct(List.Combine(List.Transform(Recombined[TableData], each Table.ColumnNames(_)))),
        ExpandedContent =
            if Table.IsEmpty(Recombined) then
                Recombined
            else
                Table.ExpandTableColumn(Recombined, "TableData", AllColumnNames),

        // Source tables have fixed-capacity rows that aren't always fully
        // used (e.g. an _Assess table has 4 assessment slots, often only
        // 1-3 filled in) — drop a row only when every one of the item's
        // own columns is blank, so an unused slot disappears without
        // hardcoding a column name specific to any one item type.
        FilteredBlankRows =
            if Table.IsEmpty(ExpandedContent) or List.IsEmpty(AllColumnNames) then
                ExpandedContent
            else
                Table.SelectRows(ExpandedContent, (row) =>
                    List.AnyTrue(List.Transform(AllColumnNames, (col) => Record.Field(row, col) <> null))
                )
    in
        FilteredBlankRows;

// ---------------------------------------------------------------------
// 5. WIDE VIEWS — Meta/Hours reshaped to one row per module
// ---------------------------------------------------------------------
//
// FS_Meta and FS_Hours (etc.) come out of fnItemTable long/key-value —
// one row per (module, field), not one row per module — because that's
// their table's actual shape, and Phase 2 deliberately doesn't reshape.
// This is that reshape, factored out the same way fnItemTable is: one
// function, called once per programme for each of the two key-value
// items, rather than duplicating a pivot step 6+ times.

shared fnPivotKeyValue = (baseTable as table, keyColumn as text, valueColumn as text) as table =>
    let
        PivotValues = List.Distinct(Table.Column(baseTable, keyColumn)),
        Pivoted = Table.Pivot(baseTable, PivotValues, keyColumn, valueColumn, each List.First(_, null))
    in
        Pivoted;

// The dashboard's summary table: one row per module. Keeps only the
// columns actually worth showing — drops the join plumbing (SourceWorkbook,
// TableName, ItemSuffix, Programme, ProgCode: all constant once you're
// looking at one programme's own dashboard) and the pivot's duplicate
// columns ("Module Code"/"Module Title"/"Programme(s)" repeat ModuleCode/
// ModuleTitle/Programme under their raw Meta-field names). Adds "Hours per
// Credit" as a cheap outlier check — no external benchmark needed, just
// something to sort by and eyeball for modules that look wrong relative to
// the rest of the cohort. MissingField.UseNull guards Table.SelectColumns
// against a programme whose Hours data turns out not to have a "Total" row
// for every module — untested school-wide, so fail soft here rather than
// error, for a first concept pass.
shared fnModuleOverview = (metaWide as table, hoursWide as table) as table =>
    let
        HoursTotal = Table.SelectColumns(hoursWide, {"ModuleCode", "Total"}, MissingField.UseNull),
        Merged = Table.NestedJoin(metaWide, {"ModuleCode"}, HoursTotal, {"ModuleCode"}, "HoursData", JoinKind.LeftOuter),
        Expanded = Table.ExpandTableColumn(Merged, "HoursData", {"Total"}, {"Total Contact Hours"}),
        Selected = Table.SelectColumns(Expanded, {
            "ModuleCode", "ModuleTitle", "Level", "Semester", "Credits",
            "Module Leader", "Module Type", "Total Contact Hours"
        }),
        Typed = Table.TransformColumnTypes(Selected, {
            {"Credits", Int64.Type}, {"Level", Int64.Type}, {"Semester", Int64.Type},
            {"Total Contact Hours", Int64.Type}
        }),
        AddRatio = Table.AddColumn(Typed, "Hours per Credit", each
            if [Credits] = null or [Credits] = 0 or [Total Contact Hours] = null then null
            else Number.Round([Total Contact Hours] / [Credits], 2), Double.Type)
    in
        AddRatio;

// ---------------------------------------------------------------------
// 6. GRADUATE SKILLS COVERAGE
// ---------------------------------------------------------------------
//
// Each workbook's LISTS sheet has a "LISTS_Table" (Category, Skill) that
// every module's _Mapping table draws its dropdown values from — the
// master catalogue of graduate skills the school actually tracks.
// FS_Mapping alone can only show what IS covered; checking what's NOT
// needs this catalogue to compare against. Pulled from SourceTables (not
// SourceTablesParsed, which already filtered LISTS_Table out — its
// parsed ItemSuffix is "Table", not one of the 5 relevant items) and
// unioned across all 6 workbooks rather than trusting just one copy, in
// case they've drifted from each other.
shared GraduateSkillsCatalogue =
    let
        Matches = Table.SelectRows(SourceTables, each [TableName] = "LISTS_Table"),
        Expanded = Table.ExpandTableColumn(Matches, "TableData", {"Category", "Skill"}),
        Distinct = Table.Distinct(Table.SelectColumns(Expanded, {"Category", "Skill"}))
    in
        Distinct;

// For a programme's _Mapping table: every catalogue (Category, Skill),
// whether it's covered anywhere in that programme, by how many modules,
// and which ones — so a gap reads as Covered = FALSE, not just an
// absence you'd have to notice yourself.
shared fnSkillsCoverage = (mappingTable as table) as table =>
    let
        UsedDetail = Table.SelectColumns(mappingTable, {"ModuleCode", "ModuleTitle", "Graduate Skills Category", "Graduate Skill"}),
        RenamedDetail = Table.RenameColumns(UsedDetail, {{"Graduate Skills Category", "Category"}, {"Graduate Skill", "Skill"}}),
        Grouped = Table.Group(RenamedDetail, {"Category", "Skill"}, {
            {"Modules Covering", each Text.Combine(List.Distinct(List.RemoveNulls([ModuleTitle])), "; "), type text},
            {"Module Count", each List.Count(List.Distinct(List.RemoveNulls([ModuleCode]))), Int64.Type}
        }),
        Merged = Table.NestedJoin(GraduateSkillsCatalogue, {"Category", "Skill"}, Grouped, {"Category", "Skill"}, "Match", JoinKind.LeftOuter),
        Expanded = Table.ExpandTableColumn(Merged, "Match", {"Modules Covering", "Module Count"}, {"Modules Covering", "Module Count"}),
        FillCount = Table.ReplaceValue(Expanded, null, 0, Replacer.ReplaceValue, {"Module Count"}),
        AddCovered = Table.AddColumn(FillCount, "Covered", each [Module Count] > 0, type logical)
    in
        AddCovered;

// ---------------------------------------------------------------------
// 7. GENERATED QUERIES — one per (programme x item), plus school-wide
// ---------------------------------------------------------------------

// --- per-programme -----------------------------------------------------

// Football Science
shared FS_Meta = fnItemTable("Football Science", "Meta");
shared FS_LO = fnItemTable("Football Science", "LO");
shared FS_Assess = fnItemTable("Football Science", "Assess");
shared FS_Hours = fnItemTable("Football Science", "Hours");
shared FS_Mapping = fnItemTable("Football Science", "Mapping");
shared FS_Meta_Wide = fnPivotKeyValue(FS_Meta, "Module Data", "Details");
shared FS_Hours_Wide = fnPivotKeyValue(FS_Hours, "Component", "Contact Hours");
shared FS_ModuleOverview = fnModuleOverview(FS_Meta_Wide, FS_Hours_Wide);
shared FS_SkillsCoverage = fnSkillsCoverage(FS_Mapping);

// Physical Education
shared PE_Meta = fnItemTable("Physical Education", "Meta");
shared PE_LO = fnItemTable("Physical Education", "LO");
shared PE_Assess = fnItemTable("Physical Education", "Assess");
shared PE_Hours = fnItemTable("Physical Education", "Hours");
shared PE_Mapping = fnItemTable("Physical Education", "Mapping");
shared PE_Meta_Wide = fnPivotKeyValue(PE_Meta, "Module Data", "Details");
shared PE_Hours_Wide = fnPivotKeyValue(PE_Hours, "Component", "Contact Hours");
shared PE_ModuleOverview = fnModuleOverview(PE_Meta_Wide, PE_Hours_Wide);
shared PE_SkillsCoverage = fnSkillsCoverage(PE_Mapping);

// Sport and Exercise Science
shared SES_Meta = fnItemTable("Sport and Exercise Science", "Meta");
shared SES_LO = fnItemTable("Sport and Exercise Science", "LO");
shared SES_Assess = fnItemTable("Sport and Exercise Science", "Assess");
shared SES_Hours = fnItemTable("Sport and Exercise Science", "Hours");
shared SES_Mapping = fnItemTable("Sport and Exercise Science", "Mapping");
shared SES_Meta_Wide = fnPivotKeyValue(SES_Meta, "Module Data", "Details");
shared SES_Hours_Wide = fnPivotKeyValue(SES_Hours, "Component", "Contact Hours");
shared SES_ModuleOverview = fnModuleOverview(SES_Meta_Wide, SES_Hours_Wide);
shared SES_SkillsCoverage = fnSkillsCoverage(SES_Mapping);

// Sport Coaching
shared COACH_Meta = fnItemTable("Sport Coaching", "Meta");
shared COACH_LO = fnItemTable("Sport Coaching", "LO");
shared COACH_Assess = fnItemTable("Sport Coaching", "Assess");
shared COACH_Hours = fnItemTable("Sport Coaching", "Hours");
shared COACH_Mapping = fnItemTable("Sport Coaching", "Mapping");
shared COACH_Meta_Wide = fnPivotKeyValue(COACH_Meta, "Module Data", "Details");
shared COACH_Hours_Wide = fnPivotKeyValue(COACH_Hours, "Component", "Contact Hours");
shared COACH_ModuleOverview = fnModuleOverview(COACH_Meta_Wide, COACH_Hours_Wide);
shared COACH_SkillsCoverage = fnSkillsCoverage(COACH_Mapping);

// Sport Nutrition
shared NUTR_Meta = fnItemTable("Sport Nutrition", "Meta");
shared NUTR_LO = fnItemTable("Sport Nutrition", "LO");
shared NUTR_Assess = fnItemTable("Sport Nutrition", "Assess");
shared NUTR_Hours = fnItemTable("Sport Nutrition", "Hours");
shared NUTR_Mapping = fnItemTable("Sport Nutrition", "Mapping");
shared NUTR_Meta_Wide = fnPivotKeyValue(NUTR_Meta, "Module Data", "Details");
shared NUTR_Hours_Wide = fnPivotKeyValue(NUTR_Hours, "Component", "Contact Hours");
shared NUTR_ModuleOverview = fnModuleOverview(NUTR_Meta_Wide, NUTR_Hours_Wide);
shared NUTR_SkillsCoverage = fnSkillsCoverage(NUTR_Mapping);

// Sport Psychology
shared PSYC_Meta = fnItemTable("Sport Psychology", "Meta");
shared PSYC_LO = fnItemTable("Sport Psychology", "LO");
shared PSYC_Assess = fnItemTable("Sport Psychology", "Assess");
shared PSYC_Hours = fnItemTable("Sport Psychology", "Hours");
shared PSYC_Mapping = fnItemTable("Sport Psychology", "Mapping");
shared PSYC_Meta_Wide = fnPivotKeyValue(PSYC_Meta, "Module Data", "Details");
shared PSYC_Hours_Wide = fnPivotKeyValue(PSYC_Hours, "Component", "Contact Hours");
shared PSYC_ModuleOverview = fnModuleOverview(PSYC_Meta_Wide, PSYC_Hours_Wide);
shared PSYC_SkillsCoverage = fnSkillsCoverage(PSYC_Mapping);

// --- school-wide (all programmes, unfiltered) ---------------------------

shared All_Meta = fnItemTable(null, "Meta");
shared All_LO = fnItemTable(null, "LO");
shared All_Assess = fnItemTable(null, "Assess");
shared All_Hours = fnItemTable(null, "Hours");
shared All_Mapping = fnItemTable(null, "Mapping");
